# Generated by Django 5.0 on 2023-12-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=60, verbose_name='Car model')),
                ('price', models.PositiveIntegerField(max_length=60, verbose_name='Car price')),
            ],
        ),
    ]
