# Generated by Django 5.0 on 2023-12-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_car_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Book name')),
                ('page', models.PositiveBigIntegerField(verbose_name='Book pages')),
                ('image', models.ImageField(upload_to='book', verbose_name='Book image')),
            ],
        ),
    ]
