# Generated by Django 5.0 on 2023-12-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Film name')),
                ('lenghth', models.PositiveIntegerField(verbose_name='Film length')),
            ],
        ),
    ]
